"""003_add_last_training

Revision ID: 003_add_last_training
Revises: 002_training_date
Create Date: 2026-01-29 23:35:05.326105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_add_last_training'
down_revision: Union[str, None] = '002_training_date'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('last_training_generation_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_sessions_athlete_id'), 'chat_sessions', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_athlete_id'), table_name='chat_sessions')
    op.drop_column('athletes', 'last_training_generation_at')
    # ### end Alembic commands ###
