"""add inactive_since to athletes

Revision ID: 225a9b5a26e4
Revises: 006
Create Date: 2026-02-27 20:53:49.840196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225a9b5a26e4'
down_revision: Union[str, Sequence[str], None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('inactive_since', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_athletes_status'), table_name='athletes')
    op.create_index(op.f('ix_athletes_training_status'), 'athletes', ['training_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athletes_training_status'), table_name='athletes')
    op.create_index(op.f('ix_athletes_status'), 'athletes', ['training_status'], unique=False)
    op.drop_column('athletes', 'inactive_since')
    # ### end Alembic commands ###
