"""initial_schema

Revision ID: 7143a39f5064
Revises: 
Create Date: 2026-01-19 22:10:32.686238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7143a39f5064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('athlete_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_chat_sessions_athlete_id'), 'chat_sessions', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_athlete_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'athlete_id')
    # ### end Alembic commands ###
