"""
Constantes relacionadas con sesiones de consulta de entrenamientos.
Define estados, atletas válidos y configuraciones de sesión.
"""
from enum import Enum


class SessionStatus(str, Enum):
    """Estados posibles de una sesión de consulta de entrenamientos."""
    INITIALIZING = "initializing"
    SELECTING_ATHLETE = "selecting_athlete"
    ACTIVE = "active"
    PAUSED = "paused"
    CLOSED = "closed"
    ERROR = "error"


# Lista de atletas válidos en el sistema (importados desde TrainingPeaks CSV)
VALID_ATHLETES = [
    "Ana De los Rios",
    "Carlos Acalco",
    "Jose Alejandro Gonzalez Mejia",
    "Danna Alvarez",
    "Luis Andres",
    "Luis Angel",
    "Emilio Antun",
    "Raul Araujo",
    "Pablo Arouesty",
    "Estefania Avendano",
    "Sara Behar",
    "Eugenio Boehringer",
    "Victoria Bujaidar",
    "Emilio Cabrera Escobedo",
    "Adrian Calderon",
    "Aaron Carrillo Ruiz",
    "Leonardo Cavazos",
    "Miranda Cepeda",
    "Esteban Chinchilla",
    "Hector dargence",
    "Abiezer Davila",
    "Jeannine De Anda",
    "Fernanda Del Bosque",
    "Alons Diaz Procel",
    "Paola Elizalde",
    "Luis Enrique Rivas Awerhoff",
    "Angel Garcia",
    "Gustavo Gardoni",
    "Alfonso Gonzalez Padilla",
    "Daniela gonzalez",
    "Pablo Gonzalez",
    "Jorge Grinberg",
    "Esteban Herrera",
    "Arturo Hinojosa",
    "Alan Huerta",
    "Melissa Lajud",
    "Allison Leos",
    "Rebecca Llano",
    "Santiago Madrid",
    "Ana Magana",
    "Gerardo Manjarres",
    "Jose Maria Aja",
    "KATIA MARIA CANTU FLORES",
    "Alondra Marin",
    "Rocco Meraz",
    "Yeri Montiel",
    "Enrique Morales",
    "Victoria Moyeda",
    "Andrea Murillo",
    "Arturo Navarro",
    "Omar Oliver Ocana Barajas",
    "Paola Ortega",
    "Maria Paula Dorantes",
    "Andres Pelcastre",
    "Emiliano Perez Sandi",
    "EDUARDO PEREZ",
    "Sofia R Rios",
    "Ana Rebeca Luna",
    "Franciela Rico",
    "Santiago Rojas Castro",
    "Bryan Rosas Luna",
    "Roberto Rubio Peschard",
    "Mauricio Ruiz",
    "Alberto Runes Naser",
    "Alejandro Salinas",
    "Mauricio Santoyo",
    "Daniel Schulz",
    "Mario Shamir",
    "Gerardo Torres",
    "SOPHIA USHKOVA",
    "Liber Valezzi",
    "Lorena Chavarria Vara",
    "Maria Villanueva",
    "Daniel Villarreal",
    "Samuel Villarreal",
    "Ricardo Weiss",
    "Isaac Morales",
    "Miguel Salgado",
    "Ricardo Sanchez Ortiz",
    "David Alejandro Drexel Garza",
    "Santiago Beltran",
    "Octavio Garcia",
    "Armando Hernandez",
    "Regina Martinez",
    "Barbara Montes De Oca",
    "Christian Mooney",
    "Randal Picard",
    "Lore Saldana",
    "Cecilia Sanchez",
    "Christian Villagrana",
    "Julian Villagrana",
    "Miguel Angel",
    "Alejandro Bessonart Almeida",
    "Jose Maria Arellano Serrano",
    "Rafael Ortega",
    "Luis Joaquin Perez Spindola",
    "Javier Ruiz",
    "Luis Fernando Torres Herandez",
    "Mario Veliz",
    "Hector Vieyra",
    "Emilio Herrera",
    "Diego Becerra",
    "Alejandro Perez Nino",
    "Daniel",
    "Rodrigo Alcocer",
    "Jose antonio",
    "Jose Antonio",
    "Luis Aragon",
    "Karla Aranalde Eguiarte",
    "Oscar Bastidas Garzon",
    "Regina Bours",
    "Andres Bryan",
    "Santiago Bujaidar",
    "Regina CALDERON",
    "Jesus Campos",
    "Alejandro Cantu",
    "Juan Carlos Sojo Hinojosa",
    "Aranza Carrillo",
    "Jaime Castiello",
    "Juan Chaires",
    "PABLO CHAVEZ DIAZ",
    "Maria del Sol Valadez",
    "Abril Diaz",
    "Andrea Dorantes",
    "Andres Fox",
    "Adamaris Galindo",
    "David Garcia",
    "Benjamin Hunter",
    "Rodrigo Merlos Albarran",
    "Oscar Montemayor",
    "Maria ochoa",
    "Patricio ochoa",
    "Maria Paula Perez Sandi Garcia",
    "Hector Perez Najera",
    "Raul Perez Rionda",
    "Eduardo Perez Sandi",
    "Martha Rodriguez",
    "Carlos Rodriguez",
    "Sofia Rojas",
    "Miranda Salmeron Valezzi",
    "Manuel Trigo",
    "Valentina Villanueva Garcia",
    "Tonatiuh Zarate",
    "Roberto Zepeda Rojas",
]


def is_valid_athlete(athlete_name: str) -> bool:
    """
    Verifica si el nombre del atleta es válido.
    
    Args:
        athlete_name: Nombre del atleta a verificar
        
    Returns:
        bool: True si el atleta es válido, False en caso contrario
    """
    return athlete_name in VALID_ATHLETES
